server:
  port: 607
#  address: 2409:894d:cdc:2174:69bb:3b24:d1a1:9e14
#  address: 192.168.1.106
spring:
  application:
    #应用的名称，可选
    name: compilationVSM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.16.40.100:3306/compilationVSM_backup?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: root
  data:
    redis:
      host: 10.16.40.100
      port: 6379
      database: 0
      password: root
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    root: INFO # 根日志级别
    com.ljz.com.ljz.compilationVSM: DEBUG # 指定包下的日志级别

  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  #    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志输出格式
  #    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 文件日志输出格式

  file: # 配置文件日志
    name: mylog.log # 日志文件名
    path: ./log # 日志文件路径，可根据需要更改




# 自定义字段值

role-permission: '{"student":[1000,1002,1003,1004,1005,1006,1008],"teacher":[2000,2001,2002,2003,2004,2005,2006,2008],"admin":[3000,3002,3003,3004,3005,3006,3008]}'

redis-key-prefix:
  login-info: 'login:info:'
  login-record: 'login:record:'

expire-time:
  login-info: 18000
  login-record: 19800
  token: 21600
ai-model:
  baseurl: http://192.168.1.150:6006
  freeQA: /proxy/ask_by_message
  optimize: /proxy/optimize
remote-compiler:
  baseurl: https://rapi.xjq.icu
  path: /code/run
  # 以下配置均已过期
  #  baseurl: https://www.runoob.com
  #  path: /try/compile2.php
  token: 066417defb80d038228de76ec581a50a
  #两个连续的换行符，配置文件解析有问题
  success: \n\n