server:
  port: 607
#  address: 2409:894d:cdc:2174:69bb:3b24:d1a1:9e14
#  address: 192.168.1.106
spring:
  application:
    #应用的名称，可选
    name: compilationVSM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.16.40.100:3306/compilationVSM_backup?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: root
  data:
    redis:
      host: 10.16.40.100
      port: 6379
      database: 0
      password: root
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    root: INFO # 根日志级别
    com.ljz.com.ljz.compilationVSM: DEBUG # 指定包下的日志级别

  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  #    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志输出格式
  #    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 文件日志输出格式

  file: # 配置文件日志
    name: mylog.log # 日志文件名
    path: ./log # 日志文件路径，可根据需要更改




# 自定义字段值

role-permission: '{"student":[1001,1002,2001,2002,2003,2004,9003],"teacher":[9001,1011,1012,2011,2012,2013,9002,2014,2015,2016,1013,1014,1015,1016],"admin":[8001,8002,8003,8004,8005,9010,8006,8007]}'

redis-key-prefix:
  login-info: 'login:info:'
  login-record: 'login:record:'
  lexer-testcase: 'lexer:testcase'
  bloom-filter: 'bloom:filter'
  hash-seed: 'hash:seed'
cache-key:
  exist-user: 'existUser'
  absent-user: 'absentUser'

expire-time:
  login-info: 18000
  login-record: 19800
ai-model:
  baseurl: http://192.168.1.150:6006
  freeQA: /proxy/ask_by_message
  optimize: /proxy/optimize
remote-compiler:
  baseurl: https://rapi.xjq.icu
  path: /code/run
obj-question:
  id-delimiter: ','
  answer-delimiter: '&1klB!'
  choose-weight: 5
  fill-weight: 5
oj:
  source-code:
    delimiter: 'J_H7#@g6%9Ne#!Hgrj~'
  lexer:
    testcase-weight: 5
    pd:
      number: 20
      delimiter: 'q'
info:
  teach-class:
    delimiter: '\s'
distribute:
  id-generator:
    datacenterId: 0
    workerId: 0
  lock:
    key-prefix:
      lexer-code-pd: 'lexer:code:pd:'
    timeout:
      lexer-code-pd: 300000
account:
  password:
    student: '123456'
    teacher: 'nARZ+No!n6yq6*'