server:
  port: 607
#  address: 2409:894c:c36:66c6:449a:eafb:55f2:cdd1
  address: 192.168.1.103
spring:
  application:
    #应用的名称，可选
    name: compilationVSM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.16.40.100:3306/compilationVSM?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: root
#  redis:
#    host: 192.168.153.100
#    port: 6379
#    password: 123456
#    database: 0
#  cache:
#    redis:
#      time-to-live: 1800000 #设置缓存数据的过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#reggie:
#  path: D:\1testfile\test\